#!/bin/bash -xe

# See https://gist.github.com/tvlooy/cbfbdb111a4ebad8b93e
script_dir="$(dirname $(readlink -f "$0"))"

arch=$(uname -m)

if [[ "${arch}" == armv* ]]; then
  MIRROR_URL='http://mirror.archlinuxarm.org/$arch/$repo'
else
  MIRROR_URL='http://mirrors.acm.wpi.edu/archlinux/$repo/os/$arch'
fi

pacman_conf="pacman-${arch}.conf"

docker pull lopsided/archlinux:devel
docker build -t aur-buildbot-worker \
  --build-arg MIRROR_URL="${MIRROR_URL}" \
  "${script_dir}"
docker image prune -f
docker run --rm \
    -v "$(pwd):/pkg" \
    -v "${script_dir}/${pacman_conf}:/etc/pacman.conf" \
    -e DEP_PKGS="${*:1}" \
    -e EXTRA_KEYS='5E1ABF240EE7A126' \
    -e BUILD_UID=$(id -u aur-buildbot-worker) \
    -e MIRROR_URL="${MIRROR_URL}" \
    aur-buildbot-worker --skippgpcheck --ignorearch
