#!/bin/bash -xe

# See https://gist.github.com/tvlooy/cbfbdb111a4ebad8b93e
script_dir="$(dirname $(readlink -f "$0"))"

arch=$(uname -m)

docker pull lopsided/archlinux:devel
docker build -t aur-buildbot-worker \
  --build-arg ARCH="${arch}" \
  "${script_dir}"
docker image prune -f
docker run --rm \
    -v "$(pwd):/pkg" \
    -e DEP_PKGS="${*:1}" \
    -e EXTRA_KEYS='5E1ABF240EE7A126' \
    -e BUILD_UID=$(id -u aur-buildbot-worker) \
    aur-buildbot-worker --skippgpcheck --ignorearch
