#!/bin/bash

# Correctly setup PATH
source /etc/profile

# Create build user
useradd -u ${BUILD_UID} -Um build

# Overwrite local mirror
if [ -n "${MIRROR_URL}" ]; then
	echo "Server = ${MIRROR_URL}" > /etc/pacman.d/mirrorlist
fi

for key_id in $EXTRA_KEYS; do
    echo "Adding key $key_id..."
    # Retry up to 10 times because keyservers seem to be flakey in Docker
    for i in {1..10}; do 
          pacman-key --keyserver hkp://ha.pool.sks-keyservers.net -r "${key_id}" && break
    done
    pacman-key --lsign-key "${key_id}"
done

# Update current system to latest
# if set, also install additional packages
pacman -Syu --noconfirm ${DEP_PKGS:+--needed ${DEP_PKGS}}

chown -R build /pkg

# unset docker-vars for better build
unset DEP_PKGS MIRROR_URL EXTRA_KEYS BUILD_UID

cd /pkg
su build -- makepkg $*
