#!/bin/bash

# Correctly setup PATH
source /etc/profile

# Create build user
useradd -u ${BUILD_UID} -Um build

# Overwrite local mirror
if [ -n "${MIRROR_URL}" ]; then
	echo "Server = ${MIRROR_URL}" > /etc/pacman.d/mirrorlist
fi

# Start dirmngr with IPv6 disabled to prevent random attempts to connect to 
# IPv6 addresses (which don't normally work in Docker)
dirmngr --homedir /etc/pacman.d/gnupg/ --daemon --disable-ipv6

for key_id in $EXTRA_KEYS; do
    echo "Adding key $key_id..."
    pacman-key --keyserver hkp://ha.pool.sks-keyservers.net -r "${key_id}" && break
    pacman-key --lsign-key "${key_id}"
done

# Update current system to latest
# if set, also install additional packages
pacman -Syu --noconfirm ${DEP_PKGS:+--needed ${DEP_PKGS}}

chown -R build /pkg

# unset docker-vars for better build
unset DEP_PKGS MIRROR_URL EXTRA_KEYS BUILD_UID

cd /pkg
su build -- makepkg $*
